### ISSUE TITLE
Use high-performance log print

### ISSUE THREAD

**Issue by yuhc** [utcs-scea/ava#1]
The current log print outputs to `stderr` and leads to large CPU burden and latency. We plan to improve its performance with high-performance logging libraries such as:

https://github.com/odygrd/quill
https://github.com/PlatformLab/NanoLog
https://github.com/HardySimpson/zlog

**Comment by arthurp** [comment]
Silly question: Is there any reason to have the logging turned on during real usage or performance testing? Any high-frequency logging should probably be disabled by default and only enabled by a compile flag or environment variable. If there is only low-frequency logging then we shouldn't need a fast logging framework at all.

**Comment by yuhc** [comment]
This will be used under debug mode. Today we experienced a bug that the high-volume debug message prints might crash TensorFlow (the RPC was timeout probably), and we couldn't get useful API logs for those workloads.

**Comment by yuhc** [comment]
[Katana](https://github.com/KatanaGraph/katana/blob/master/libsupport/include/katana/Logging.h) has a very good example which is based on [fmtlib](https://github.com/fmtlib/fmt).
