### ISSUE TITLE
[BUG] cmake of cudart with debug mode fails on the ava container. 

### ISSUE THREAD

**Issue by hfingler** [utcs-scea/ava#145]
**Describe the bug**
Building ava with -CMAKE_BUILD_TYPE=Debug inside the ava container w/ cuda 10.1 does not succeed. Without debug flag it does.

**To Reproduce**
Create the 10.1 container, run interactive shell and compile with
```
./generate.py -s cudart && mkdir -p build
cd build && cmake .. -DAVA_GEN_CUDART_SPEC=ON -DAVA_MANAGER_DEMO=ON -CMAKE_BUILD_TYPE=Debug
```
If `-CMAKE_BUILD_TYPE=Debug` is removed, it works fine.

**Expected behavior**
Container should be setup to compile release and debug with no errors.

**Error log**
```
Determining if the strtod_l exist failed with the following output:
...
CMakeTmp/CheckSymbolExists.c:8:19: error: ‘strtod_l’ undeclared (first use in this function); did you mean ‘strtoull’?
   return ((int*)(&strtod_l))[argc];

...

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
...
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_45ece.dir/link.txt --verbose=1
/usr/bin/cc CMakeFiles/cmTC_45ece.dir/src.c.o -o cmTC_45ece 
CMakeFiles/cmTC_45ece.dir/src.c.o: In function `main':
src.c:(.text+0x3e): undefined reference to `pthread_create'
src.c:(.text+0x4a): undefined reference to `pthread_detach'
src.c:(.text+0x56): undefined reference to `pthread_cancel'
src.c:(.text+0x67): undefined reference to `pthread_join'
src.c:(.text+0x7b): undefined reference to `pthread_atfork'
```

**Comment by hfingler** [comment]
Could be related to https://github.com/fmtlib/fmt/issues/1478

**Comment by hfingler** [comment]
Looks like the first error, related to fmt, is fixed by updating cmake in the container. So the fix should run `tools/install_dependencies.sh` in the Dockerfile.

**Comment by yuhc** [comment]
Looks the issue has been fixed. Please reopen if necessary.
