### ISSUE TITLE
[BUG] ava_*_replacement functions in spec are not exported

### ISSUE THREAD

**Issue by vancemiller** [utcs-scea/ava#182]
**Describe the bug**
In the cudart spec cudaMallocHost and cudaFreeHost are defined in a ava_begin_replacement, ava_end_replacement block. These functions are not exported in the guestlib, but seem like they should be.

**To Reproduce**
Compile cudart spec. `nm -g libguestlib.so | grep cudaMallocHost`

**Expected behavior**
Expected to see cudaMallocHost/cudaFreeHost in exported symbols.

**Comment by photoszzt** [comment]
![image](https://user-images.githubusercontent.com/1476795/122631636-a3646380-d092-11eb-948e-f14e82495cea.png)
It's missing the EXPORTED. The symbol is defined in onnx_opt spec.
